[package]
edition = "2021"
name = "kcp_handler"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
flume = "0.10.14"
gdnative = {git = "https://github.com/godot-rust/godot-rust.git", features = ["async"]}
rand = "0.8"
tokio = {version = "1", features = ["full"]}
tokio_kcp = "0.9.3"
